src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50, unique: true)]
    private ?string $Sku = null;

    #[ORM\Column(length: 250)]
    private ?string $Product_name = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $update_at = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSku(): ?string
    {
        return $this->Sku;
    }

    public function setSku(string $Sku): static
    {
        $this->Sku = $Sku;

        return $this;
    }

    public function getProductName(): ?string
    {
        return $this->Product_name;
    }

    public function setProductName(string $Product_name): static
    {
        $this->Product_name = $Product_name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdateAt(): ?\DateTimeInterface
    {
        return $this->update_at;
    }

    public function setUpdateAt(?\DateTimeInterface $update_at): static
    {
        $this->update_at = $update_at;

        return $this;
    }

    public function __toString(): string
    {
      return (string) $this->Sku. ' | ' .$this->Product_name;
    }
}

src/Controller/ProductController.php
<?php

namespace App\Controller;

use App\Entity\Product;
use App\Repository\ProductRepository;
use App\Service\CreateProduct;
use App\Service\ProductsService;
use DateTimeImmutable;
use DateTime;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/')]
class ProductController extends AbstractController
{
  #[Route('', name: 'app_product_index', methods: ['GET'])]
  public function index(ProductRepository $productRepository): Response
  {
    return $this->render('product/index.html.twig', [
      'products' => $productRepository->findAll(),
    ]);
  }

  #[Route('/new', name: 'app_product_new', methods: ['GET', 'POST'])]
  public function new(Request $request, ProductRepository $productRepository, EntityManagerInterface $entityManager, ProductsService $productsService): Response
  {
    if ($request->isMethod('POST')) {
      $products = $request->request->all();
      $skuerrors = [];
      foreach ($products['products'] as $product) {
        if ($productRepository->exists($product[0]) != []) {
          array_push($skuerrors, $product[0]);
        }
      }
      if (count($skuerrors) == 0) {
        foreach ($products['products'] as $product) {
          $newProduct = $productsService->createProductWithAllValues($product[0], $product[1], $product[2]);
          $entityManager->persist($newProduct);
          $entityManager->flush();
        }
        $this->addFlash('resultProductRequest', 'You created the products correctly!');
        return $this->redirectToRoute('app_product_index');
      } else {
        return $this->render('product/new.html.twig', [
          'errors' => $skuerrors
        ]);
      }
    }
    return $this->render('product/new.html.twig');
  }

  #[Route('/edit', name: 'app_products_edit', methods: ['GET', 'POST'])]
  public function edit(Request $request, ProductRepository $productRepository, EntityManagerInterface $entityManager, SessionInterface $session, ProductsService $productsService): Response
  {
    if ($request->isMethod('POST')) {
      $anySkuFails = false;
      $products = $request->request->all();
      foreach ($products['updatedProducts'] as $key => $product) {
        // $product[0] = NEW SKU | $product[1] = NEW DESCRIPTION | $product[2] = NEW NAME
        $sku = explode(' |', $products['oldskus'][$key]);
        // if the user doesn't specify a new sku value, that means is a empty string value. so it should update only the other fields. 
        // Also, there's no need to validate any data beccause there isn't any constraints.
        if ($product[0] == '') {
          $oldProduct = $productRepository->findOneBySku($sku[0]);
          $oldProduct = $productsService->editProductWithNoNewSku($oldProduct, $product[2], $product[1]);
          $entityManager->persist($oldProduct);
        } else {
          $oldProduct = $productRepository->findOneBySku($sku[0]);
          if ($productRepository->exists($product[0]) != []) {
            // if any SKU code that the user wants to put, exists in the database, i will not flush any of the persisted entities, and i will return a flash message.
            $anySkuFails = true;
          } else {
            // if doesn't exists any product with the new SKU that the users wants, i will persist the updated entity.
            $oldProduct = $productsService->editProductWithNewSku($oldProduct, $product[0], $product[2], $product[1]);
            $entityManager->persist($oldProduct);
          }
        }
      }
      if ($anySkuFails) {
        $this->addFlash('resultProductRequest', 'Oops... it seems that a new sku that you provided was already in the database.');
        return $this->redirectToRoute('app_product_index');
      } else {
        $entityManager->flush();
        $this->addFlash('resultProductRequest', 'You updated the products correctly!');
        return $this->redirectToRoute('app_product_index');
      }
    }
    return $this->render('product/edit.html.twig', [
      'skus' => $entityManager->getRepository(Product::class)->findAll(),
    ]);
  }
}

templates/product/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Products
{% endblock %}

{% block body %}
	<div class="d-flex justify-content-center pt-5">
		<h2 class="fw-medium text-white">Symfony Test</h2>
	</div>
	<div class="d-flex flex-column p-4 justify-content-center align-items-center">

		<form method="POST" action="{{path('app_products_edit')}}">
			<h4 class="fw-medium text-white">Edit Products</h4>
			<div id="inputdivs" class="bg-dark p-4 rounded-top d-flex flex-column gap-1">
				<div id="inputdiv-1" class="d-flex gap-2">
					<div class="d-flex flex-column">
						<label for="selectsku" class="text-white">Select a product to update</label>
						<select id="selectsku" class="rounded p-1" name="oldskus[product-1]" required>
							<option value="" selected>List of products here</option>
							{% for sku in skus %}
								<option value="{{sku}}">{{sku}}</option>
							{% endfor %}
						</select>
					</div>
					<div class="d-flex flex-column">
						<label for="newsku" class="text-white">New Sku &#40;not required&#41;</label>
						<input type="text" placeholder="new sku" id="newsku" name="updatedProducts[product-1][]">
					</div>
					<div class="d-flex flex-column">
						<label for="newDescription" class="text-white">New Description</label>
						<input type="text" placeholder="new description" id="newDescription" name="updatedProducts[product-1][]">
					</div>
					<div class="d-flex flex-column">
						<label for="newName" class="text-white">New Name</label>
						<input type="text" placeholder="new name" id="newname" name="updatedProducts[product-1][]">
					</div>
				</div>
			</div>
			<div class="d-flex gap-1 justify-content-center flex-column align-items-center">
				<button id="addButton" type="button" data-turbo="false" class="bg-dark text-white p-1 rounded-bottom border border-secondary w-100">Edit another product</button>
				<button type="submit" data-turbo="false" class="bg-dark text-white p-1 mt-3 rounded w-100">Submit</button>
				<a href="{{ path('app_product_index') }}" class="text-white mt-3">View products list</a>
			</div>
		</form>
		<script>

// i needed to use JQuery because if i paste html with StimulusJs it doesn't parse the twig directives because it isn't able to do that.
// so, in the creation form, i was able to make that form work with stimulus, but here, i need to have the twig directives working so i can map
// the values on the select. It's better than making an AJAX request everytime that the user adds a select.
const addButton = document.getElementById('addButton');
addButton.addEventListener('click', () => {
add();
})
function add() {
let lastDivId = document.getElementById('inputdivs').lastElementChild.getAttribute('id');
// im getting the last div inside my inputdivs, so i can access the id attribute and then add a new one with the values updated
// so i am able to manage the info correctly in the controller.
let lastId = lastDivId.substr(-1);
lastId++;
console.log(lastId, 'nuevo id');
$('#inputdivs').append(`<div id="inputdiv-${lastId}" class="d-flex gap-2"><div class="d-flex flex-column"><label for="selectsku" class="text-white">Select a product to update</label><select id="selectsku" class="rounded p-1" required name="oldskus[product-${lastId}]"><option value="" selected>List of products here</option> {% for sku in skus %} <option value="{{sku}}">{{sku}}</option> {% endfor %} </select></div><div class="d-flex flex-column"><label for="newsku" class="text-white">New Sku &#40;not required&#41;</label><input type="text" placeholder="new sku" id="newsku" name="updatedProducts[product-${lastId}][]"></div><div class="d-flex flex-column"><label for="newDescription" class="text-white">New Description</label> <input type="text" placeholder="new description" id="newDescription" name="updatedProducts[product-${lastId}][]"></div><div class="d-flex flex-column"><label for="newName" class="text-white">New Name</label> <input type="text" placeholder="new name" id="newname" name="updatedProducts[product-${lastId}][]"></div></div>`)
}

		</script>
	{% endblock %}

templates/product/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Symfony Test
{% endblock %}

{% block body %}
	{# {% if app.user %}
	      <p> estas logueado como {{app.user.email}}</p>
	    {% endif %} #}
	<div class="w-100 d-flex flex-column justify-content-center">
		<div class="d-flex justify-content-center pt-5">
			<h2 class="fw-medium text-white">Symfony Test</h2>
		</div>
		<div class="w-100 pe-5 ps-5 pt-3 pb-3">
    {% for message in app.flashes('resultProductRequest') %}
		<p class="flash-notice bg-white p-2 rounded fw-medium">
			{{ message }}
		</p>
	{% endfor %}
      <h4 class="fw-medium text-white">Products List</h4>
			<table class="table-dark table-striped-columns table">
				<thead>
					<tr>
						<th class="fw-medium">Id</th>
						<th class="fw-medium">Sku</th>
						<th class="fw-medium">Product_name</th>
						<th class="fw-medium">Description</th>
						<th class="fw-medium">Created_at</th>
						<th class="fw-medium">Update_at</th>
					</tr>
				</thead>
				<tbody>
					{% for product in products %}
						<tr>
							<td class="fw-light">{{ product.id }}</td>
							<td class="fw-light">{{ product.Sku }}</td>
							<td class="fw-light">{{ product.ProductName }}</td>
							<td class="fw-light">{{ product.description }}</td>
							<td class="fw-light">{{ product.createdAt ? product.createdAt|date('Y-m-d H:i:s') : '' }}</td>
							<td class="fw-light">{{ product.updateAt ? product.updateAt|date('Y-m-d H:i:s') : '' }}</td>
						</tr>
					{% else %}
						<tr>
							<td colspan="7">no records found</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
		<div class="d-flex gap-2 justify-content-center pe-5 ps-5 pb-5">
			<a href="{{ path('app_products_edit')}}" class="bg-dark text-white p-2 rounded">edit products</a>
			<a href="{{ path('app_product_new') }}" class="bg-primary text-white p-2 rounded">Create new</a>
		</div>
	</div>
{% endblock %}

templates/product/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Product
{% endblock %}

{% block body %}
	{% if (errors is defined) %}
		{% for error in errors %}
			<p>the value sku:
				{{error}}
				has already been taken</p>
		{% endfor %}
	{% endif %}
  <div class="d-flex justify-content-center pt-5">
			<h2 class="fw-medium text-white">Symfony Test</h2>
		</div>
	<div class="d-flex flex-column p-4 justify-content-center align-items-center">
  
		<form method="POST" action="{{path('app_product_new')}}" data-controller="productsForm">
    <h4 class="fw-medium text-white">Store Products</h4>
			<div id="inputdivs" class="bg-dark p-4 rounded-top d-flex flex-column gap-1">
				<div id="inputdiv-1" class="d-flex gap-2">
					<div class="d-flex flex-column">
						<label for="sku" class="text-white">SKU</label>
						<input type="text" placeholder="sku" name="products[product-1][]" required>
					</div>
					<div class="d-flex flex-column">
						<label for="name" class="text-white">Name</label>
						<input type="text" placeholder="name" name="products[product-1][]" required>
					</div>
					<div class="d-flex flex-column">
						<label for="description" class="text-white">Description</label>
						<input type="text" placeholder="description" name="products[product-1][]">
					</div>
				</div>
			</div>
      <div class="d-flex gap-1 justify-content-center flex-column align-items-center">
        <button type="button" data-action="click->productsForm#addAnotherProductIndex" class="bg-dark text-white p-1 rounded-bottom border border-secondary w-100">Add item</button>
        <button data-turbo="false" type="submit" class="bg-dark text-white p-1 mt-3 rounded w-100">Submit</button>
        <a href="{{ path('app_product_index') }}" class="text-white mt-3">View products list</a>
      </div>
		</form>
	</div>
	
{% endblock %}